### ISSUE TITLE
[API] GET /categories

### ISSUE THREAD

**Issue by JoelKlint** [careerfairsystems/nexpo#11]

**Comment by Oscar-Rydh** [comment]
Vet du hur man får test databasen att resetta mellan testcasen/körningarna, jag hittar inte rätt på det nämligen.

Annars verkar denna fungera, när man testar för hand

**Comment by JoelKlint** [comment]
Den gör det på auto så länge de inte körs async. De körs async om man explicit anger det högst upp i testfilen

**Comment by Oscar-Rydh** [comment]
Alright, vet du vilken flagga som gör att den kör sync, tror det är problemet nämligen

**Comment by Oscar-Rydh** [comment]
nvm hitta

**Comment by Oscar-Rydh** [comment]
Dock resettar den ej databasen mellan körningarna ändå, aja släpper detta tills imorn nu
