### ISSUE TITLE
[API] Find productive way to document endpoints

### ISSUE THREAD

**Issue by JoelKlint** [careerfairsystems/nexpo#20]
Det här verkar ganska schysst.
https://github.com/lord/slate

**Comment by JoelKlint** [comment]
Finns ny en docs branch där man kan ändra docs. Innehållet i docsen är "hello world" nu, men finns att se på länken i description för repot (https://careerfairsystems.github.io/nexpo/)

**Comment by JoelKlint** [comment]
Börjar landa i idén att ha docs i en annan branch är rätt jobbigt. Kanske värt att hitta ett verktyg där man skriver docs inline i koden, som sedan extraheras. Alternativt att sätta upp ett "nexpo-docs" repo och ha docsen där, på samma sätt som vi har en en separat branch idag

**Comment by Oscar-Rydh** [comment]
Mitt förslag är att göra så som jag gör på jobbet, dvs att skriva docsen som kommentarer i koden som sedan genererar ett snyggt webb gränssnitt mha av verktyg, ex apidocs. Dessa genereras då på push och har en egen endpoint, ex /apidocs

**Comment by Oscar-Rydh** [comment]
Cool! I så fall blir kommenterandet en naturlig del av kodandet!

**Comment by JoelKlint** [comment]
Konfade nyss detta, och skrev något exempeltest i #43
