### ISSUE TITLE
[Production] Skapa CI flow

### ISSUE THREAD

**Issue by JoelKlint** [careerfairsystems/nexpo#21]
Jag tänker nåt i stil med:
Github push --> Travis kör tester --> on success: deploy to heroku

Om dokumentation är statisk på github pages borde det deployas automatiskt on push.

Jag tror vi kommer behöva göra separata server/client repon för detta, alternativt integrera react med phoenix på ett bra sätt. Annars kan eventuellt heroku/travis bli förvirrade

**Comment by JoelKlint** [comment]
Att integrera phoenix och react:http://www.east5th.co/blog/2017/04/03/using-create-react-app-with-phoenix/

Kanske går att göra nåt liknande, där man kör phoenixtester, reacttester samt bygger react frontenden innan deploy

**Comment by Oscar-Rydh** [comment]
Tror du vi har något speciellt heroku acc från kårens sida?

**Comment by Oscar-Rydh** [comment]
Tänkte testa detta imorn: https://lord.io/blog/2014/travis-multiple-subdirs/

**Comment by PeterSkopal** [comment]
Det finns ett arkad-konto kopplat till min mail (it.arkad@tlth.se) där jag kan lägga till er som collaborators på en app.

**Comment by Oscar-Rydh** [comment]
Coolt, pm mig gärna lösen om det går :)

**Comment by JoelKlint** [comment]
Nice @Oscar-Rydh. Vi måste knäcka nöten var react-frontenden ska serveras ifrån sen också. Jag tänker mig att phoenix kan få vara ansvarig för det, men då måste vi flytta den enligt detta http://www.east5th.co/blog/2017/04/03/using-create-react-app-with-phoenix/

Bara så du är med på att strukturen kan ändras

**Comment by Oscar-Rydh** [comment]
Alright, men vi får väll se hur stort problem det blir sen! Just nu sätter jag detta on hold, då 
@PeterSkopal Måste tillåta travis att komma åt repot

**Comment by Oscar-Rydh** [comment]
@PeterSkopal Se slack, fick tydligen inte full access :/

**Comment by JoelKlint** [comment]
Projektet är nu konfat för Heroku, så att allting byggs på rätt sätt efter https://github.com/careerfairsystems/nexpo/commit/12f153fefeec069eb71d0f4b940afc9b0aee7efe. Allting dokumenterat i README
