### ISSUE TITLE
[CORS] Ska server tillåta connections från alla?

### ISSUE THREAD

**Issue by JoelKlint** [careerfairsystems/nexpo#23]

**Comment by Oscar-Rydh** [comment]
Hur menar du?

**Comment by JoelKlint** [comment]
Servern accepterar inte requests från andra än sig själv from start. För att React-frontenden ska kunna hämta saker över HTTP så var jag tvungen att tillåta localhost:3000 göra requests. Jag tillät alla, men vet inte om det är det vi vill. Vet inte om detta spelar någon roll.

Till sen när appar ska använda servern så kommer förmodigen alla ip-adresser vara tillåtna
