### ISSUE TITLE
[ReactRouter] Going to a link directly gives elixir Page Not Found

### ISSUE THREAD

**Issue by JoelKlint** [careerfairsystems/nexpo#24]

**Comment by Oscar-Rydh** [comment]
Jag får inte detta felet av någon anledning. Jag får: `{"data":null}`

**Comment by JoelKlint** [comment]
Jag med, därav issuet

**Comment by Oscar-Rydh** [comment]
Ahh fatta det fel då, läste headlinen som om att man fick 404 ^^

**Comment by JoelKlint** [comment]
Problemet måste vara att react bara nås om man går in på base url, annars fastnar man i Phoenix router
