### ISSUE TITLE
["blip"-API] Method for getting student information (as a student)

### ISSUE THREAD

**Issue by PerFilip** [careerfairsystems/nexpo#319]
This is the same information as the company sees,with the exception of rating/'company comments'.

@ GET
RETURN : student json object

**Comment by mu1664al-s** [comment]
This API exists, but is not documented yet.

**Comment by PerFilip** [comment]
Opening again until some tests are done and documentation is written

**Comment by PerFilip** [comment]
Documentation is now written and can be found in the documentation under User
