### ISSUE TITLE
New student info fields

### ISSUE THREAD

**Issue by Alexander-Mjoberg** [careerfairsystems/nexpo#342]
When signing up a student should be able to add the following additional information about themselves

**Graduation year:** 
**Master:** Dropdown list, will give alternatives later. Must be populated depending on what program they choose. 
**Interested in:** Dropdown list: Foreign Opportunities, Internships, Part-time job, Summer jobs, Thesis, Trainee employment
**linkedIn**: Link to their linkedIn

**Comment by ViktorClaesson** [comment]
done
