### ISSUE TITLE
We need dat' CV code fam

### ISSUE THREAD

**Issue by Alexander-Mjoberg** [careerfairsystems/nexpo#347]
I apppen får vi en URL till Amazon S3 där cv'et lagras, men får access denied när vi följer länken. Vi behöver härma hur ni gör när ni gör för att komma åt CV. Antingen behöver vi era secret keys eller att ni öppnar en nexpo url där man kan läsa cv't i webläsaren. Url'en vi har är : https://nexpo.s3.amazonaws.com/uploads/students/624/cv/sv/b1d9cd5769a77b7ba27802556ceb59f25641f11705e3a031c74ceb3af9e8afa0.pdf

Please halp.

**Comment by ViktorClaesson** [comment]
Har skickat api nycklarna till dig
