### ISSUE TITLE
[API] Create tests for /companies

### ISSUE THREAD

**Issue by Oscar-Rydh** [careerfairsystems/nexpo#5]
Currently there are no tests, not so tdd.

**Comment by JoelKlint** [comment]
För vadå? @Oscar-Rydh

**Comment by Oscar-Rydh** [comment]
Lol tror jag stanna mitt i meningen här ^^

**Comment by Oscar-Rydh** [comment]
La mest till den för att inte glömma för det som var implementerat

**Comment by Oscar-Rydh** [comment]
Done
